packages:
  - 'packages/*'
  - 'apps/*'

catalog:
  # React ecosystem
  react: ^18.3.1
  react-dom: ^18.3.1
  '@types/react': ^18.3.12
  '@types/react-dom': ^18.3.1

  # Next.js
  next: ^15.0.3
  '@next/bundle-analyzer': ^15.0.3

  # TypeScript
  typescript: ^5.6.3
  '@types/node': ^22.9.0

  # Styling
  tailwindcss: ^3.4.14
  autoprefixer: ^10.4.20
  postcss: ^8.4.49
  '@tailwindcss/typography': ^0.5.15
  '@tailwindcss/forms': ^0.5.9

  # UI Libraries
  '@radix-ui/react-slot': ^1.1.0
  '@radix-ui/react-dropdown-menu': ^2.1.2
  '@radix-ui/react-dialog': ^1.1.2
  '@radix-ui/react-toast': ^1.2.2
  '@radix-ui/react-tooltip': ^1.1.3
  '@radix-ui/react-popover': ^1.1.2
  '@radix-ui/react-select': ^2.1.2
  '@radix-ui/react-checkbox': ^1.1.2
  '@radix-ui/react-radio-group': ^1.2.1
  '@radix-ui/react-switch': ^1.1.1
  '@radix-ui/react-tabs': ^1.1.1
  '@radix-ui/react-accordion': ^1.2.1
  '@radix-ui/react-avatar': ^1.1.1
  '@radix-ui/react-badge': ^1.1.0
  '@radix-ui/react-progress': ^1.1.0
  '@radix-ui/react-label': ^2.1.0

  # Utilities
  clsx: ^2.1.1
  tailwind-merge: ^2.5.4
  class-variance-authority: ^0.7.1
  lucide-react: ^0.456.0
  nanoid: ^5.0.8
  date-fns: ^4.1.0

  # Animation
  framer-motion: ^11.11.17

  # State Management
  zustand: ^5.0.1
  '@tanstack/react-query': ^5.59.16
  '@tanstack/react-query-devtools': ^5.59.16

  # Forms
  react-hook-form: ^7.53.2
  '@hookform/resolvers': ^3.9.1
  zod: ^3.23.8

  # Authentication
  next-auth: ^4.24.10

  # Database
  '@prisma/client': ^5.22.0
  prisma: ^5.22.0

  # SEO
  next-seo: ^6.6.0

  # Theming
  next-themes: ^0.4.3

  # Image Processing
  sharp: ^0.33.5

  # Development Tools
  eslint: ^8.57.1
  eslint-config-next: ^15.0.3
  '@typescript-eslint/eslint-plugin': ^8.15.0
  '@typescript-eslint/parser': ^8.15.0
  prettier: ^3.3.3
  prettier-plugin-tailwindcss: ^0.6.8

  # Testing
  vitest: ^2.1.4
  '@vitejs/plugin-react': ^4.3.3
  jsdom: ^25.0.1
  '@testing-library/react': ^16.0.1
  '@testing-library/jest-dom': ^6.6.3
  '@vitest/coverage-v8': ^2.1.4
  '@playwright/test': ^1.48.2

  # Build Tools
  tsup: ^8.3.5
  cross-env: ^7.0.3

  # Linting & Formatting
  husky: ^9.1.6
  lint-staged: ^15.2.10

  # Storybook
  storybook: ^8.4.6
  '@storybook/react': ^8.4.6
  '@storybook/react-vite': ^8.4.6
  '@storybook/addon-essentials': ^8.4.6
  '@storybook/addon-interactions': ^8.4.6
  '@storybook/addon-links': ^8.4.6

ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - prisma
  - sharp