// Local Storage Hooks
export {
  useLocalStorage,
  useLocalStorageState,
  useLocalStorageBoolean,
  useLocalStorageString,
  useLocalStorageNumber,
  useLocalStorageArray,
  useLocalStorageObject,
  useLocalStorageTheme,
  useLocalStoragePreferences,
  useLocalStorageRecent,
  useLocalStorageForm,
  type UserPreferences,
} from './use-local-storage'

// Media Query Hooks
export {
  useMediaQuery,
  useIsMobile,
  useIsTablet,
  useIsDesktop,
  useIsSmall,
  useIsMedium,
  useIsLarge,
  useIsExtraLarge,
  useIs2ExtraLarge,
  useIsPortrait,
  useIsLandscape,
  usePrefersDarkMode,
  usePrefersLightMode,
  usePrefersReducedMotion,
  usePrefersHighContrast,
  useSupportsHover,
  useSupportsPointerFine,
  useSupportsPointerCoarse,
  useBreakpoint,
  useBreakpoints,
  useResponsiveValue,
  useViewportSize,
  useMinWidth,
  useMaxWidth,
  useWidthRange,
  useDevicePixelRatio,
  useIsTouchDevice,
  useCombinedMediaQuery,
  useContainerQuery,
} from './use-media-query'

// Debounce Hooks
export {
  useDebounce,
  useDebouncedCallback,
  useImmediateDebounce,
  useDebouncedSearch,
  useDebouncedState,
  useDebouncedWithPending,
  useDebouncedApi,
  useDebouncedValidation,
  useDebouncedAutoSave,
} from './use-debounce'